language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: true
script: mvn -Dmaven.test.skip=true clean install
notifications:
  slack:
    rooms:
      secure: E+4+2yR9VFR48dyNb9vahES3WOG53V0/DKtjzImqYCUubqi5E6lMWUFvnD5vj15bViKYIlkpkQwWe/EbTQSkyk7/NWX444b6GcF4GKbly7w2WQCRcTxl4pTtsAzXKczDutdS7NXX3sf/PEep6eGHl2MMkmIgdz3qIn+A+YIsLcfxqeOPVClB0jJMLhG7anU5a6cNgWi6MMzz8ifa0HqB/oHYsJap2/SfcBpSZ4p89YIxUn2U6RHS+Yrf0FlcfOEqihn4QchQw6Vp1ggsTBErdvk9OW371VHEXMI/ADBzNdI1+ETOT8vlKDhMXGDyIOE06EMV1hRoVE2VBsMaZzzYhKOvy4V+/WutFJfa1gaY0hVbWy7eWFbyZYD5QAEmeqUmeTc3e639KS0WgUTZGzxS0aFqagnK23Bbjwl1Sl+5pb30V+dpAj5jjIaPoEcFlMLb0BxN4asXRnLBb3PLUiZtgU98ZhOKxlcOcLHMyDEr0YceDOfx8cN3Eyg1gFR7AwkHz6cH5s1DpGSAVh+neY5JzYf0QNGERVaDUeRrAYqWPn9SkLlwrBZukjIrKJN0MMIVUwTcGfLbmjjbDOA5RoGYECHM6kRZOVB7nkfCasMzo5RuQgARcLrtS0UXgo1VFY6ihQsTogNLq37CbUKnicHZSEBvC5+v8l3+kOmUV/+aSn0=
