language: java
jdk:
- oraclejdk5
cache:
  directories:
  - $HOME/.m2
before_install:
- export TZ=Pacific/Noumea
install: mvn clean install -Dmaven.javadoc.skip=true -B -V
notifications:
  slack: dsi-mairie-noumea:MxlOz1t5uMHw8BYH0qjlv0R1
